### ISSUE TITLE
Add Biotech center seminars into MDTP orientation talk

### ISSUE THREAD

**Issue by sstevens2** [ComBEE-UW-Madison/presentations#1]
@lizilla1993 or @sstevens2 ?

**Comment by sstevens2** [comment]
Did this and pushed in commit aeefb1a  @lizilla1993  can you take a look at this?  It is sort of a lame slide

**Comment by elizabethmcd** [comment]
Should there be examples of types of workshops held? Like the mothur ones Kim did?

**Comment by sstevens2** [comment]
Sure!  I'll fix it later today.
Sarah

**Comment by sstevens2** [comment]
Hey @lizilla1993, Does the new version in commit 97704a77b look better?  It was kind of empty before and I added a little info to what is covered in SWC/DC workshops. If so, please close this issue but additional comments still welcome of course!

**Comment by elizabethmcd** [comment]
Biotech center slide looks good. "Throughput" is one word, at least it is on the CHTC website.

**Comment by sstevens2** [comment]
Fixed. :-D
Sarah
